# Generated by Django 5.0.4 on 2024-06-26 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_api', '0002_cse_staff_staff_email_hdr_student_student_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cse_staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cse_staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hdr_student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hdr_student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cse_staff',
            name='staff_email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cse_staff',
            name='staff_zid',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hdr_student',
            name='student_email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='hdr_student',
            name='student_zid',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
