# Generated by Django 5.0.4 on 2024-06-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_api', '0003_cse_staff_user_hdr_student_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cse_staff',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hdr_student',
            name='user',
        ),
        migrations.AlterField(
            model_name='cse_staff',
            name='staff_email',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cse_staff',
            name='staff_faculty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cse_staff',
            name='staff_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cse_staff',
            name='staff_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='cse_staff',
            name='staff_role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cse_staff',
            name='staff_school',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cse_staff',
            name='staff_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hdr_student',
            name='student_degree',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hdr_student',
            name='student_email',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='hdr_student',
            name='student_faculty',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hdr_student',
            name='student_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hdr_student',
            name='student_password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='hdr_student',
            name='student_role',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hdr_student',
            name='student_school',
            field=models.CharField(max_length=100),
        ),
    ]
