# Generated by Django 5.0.4 on 2024-07-02 11:52

import acsess_api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_api', '0004_remove_cse_staff_user_remove_hdr_student_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cse_staff',
            name='user',
            field=models.OneToOneField(default=acsess_api.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hdr_student',
            name='user',
            field=models.OneToOneField(default=acsess_api.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
