# Generated by Django 5.0.4 on 2024-07-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_api', '0007_room_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='hotdesk',
            fields=[
                ('hotdesk_id', models.AutoField(primary_key=True, serialize=False)),
                ('hotdesk_number', models.CharField(max_length=100)),
                ('hotdesk_location', models.CharField(max_length=200)),
                ('hotdesk_floor', models.IntegerField()),
                ('hotdesk_description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
