# Generated by Django 5.0.4 on 2024-07-14 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_api', '0009_remove_booking_id_remove_booking_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pending_booking',
            name='booking_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='acsess_api.booking'),
            preserve_default=False,
        ),
    ]
