# Generated by Django 5.0.4 on 2024-07-27 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_api', '0014_booking_created_at_booking_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_history',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='acsess_api.booking'),
        ),
    ]
