# Generated by Django 5.0.4 on 2024-08-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_api', '0019_remove_booking_checked_out_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotdesk',
            name='hotdesk_utilities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
