# Generated by Django 5.0.4 on 2024-08-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_api', '0020_hotdesk_hotdesk_utilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cse_staff',
            name='staff_password',
        ),
        migrations.RemoveField(
            model_name='hdr_student',
            name='student_password',
        ),
    ]
