# Generated by Django 5.0.4 on 2024-08-04 09:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acsess_api', '0021_remove_cse_staff_staff_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotdesk',
            name='hotdesk_coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, null=True, size=None),
        ),
    ]
